Repository asyncapi/studio, pull requests merged in 2021-12, with the labels that each got.

#208 chore: add CODEOWNERS file
  CODEOWNERS
Labels: enhancement

#211 fix: some security issues
  package-lock.json
Labels: ready-to-merge

#190 feat: add options for editor and templates
  config-overrides.js
  craco.config.js
  package-lock.json
  package.json
  src/components/Content.tsx
  src/components/Editor/MonacoWrapper.tsx
  src/components/Modals/Settings/SettingsModal.tsx
  src/components/Modals/Settings/SettingsTabs.tsx
  src/components/Navigation.tsx
  src/components/Sidebar.tsx
  src/components/Template/HTMLWrapper.tsx
  src/components/Template/Template.tsx
  src/components/Template/TemplateSidebar.tsx
  src/components/Terminal/Terminal.tsx
  src/components/Terminal/TerminalInfo.tsx
  src/components/Visualiser/FlowDiagram.tsx
  src/components/Visualiser/Visualiser.tsx
  src/components/Visualiser/VisualiserTemplate.tsx
  src/components/Visualiser/index.ts
  src/components/common/Switch.tsx
  src/components/common/index.ts
  src/react-app-env.d.ts
  src/services/editor.service.tsx
  src/services/navigation.service.ts
  src/services/specification.service.ts
  src/state/app.ts
  src/state/editor.ts
  src/state/index.ts
  src/state/settings.ts
  src/state/sidebar.ts
  src/state/template.ts
  src/studio.tsx
  tailwind.config.js
Labels: enhancement, ready-to-merge
