Repository asyncapi/studio, pull requests merged in 2022-02, with the labels that each got.

#254 feat: support 2.3.0 version of spec
  package-lock.json
  package.json
  src/state/editor.ts
Labels: autoapproved, ready-to-merge

#201 feat: move template selection into modal UI
  src/components/Content.tsx
  src/components/Modals/ConfirmModal.tsx
  src/components/Modals/NewFileModal.tsx
  src/components/NewFile/index.tsx
  src/components/Sidebar.tsx
  src/examples/index.tsx
  src/examples/real-world/gitter-streaming.yml
  src/examples/real-world/slack-rtm.yml
  src/examples/simple.yml
  src/examples/streetlights-kafka.yml
  src/examples/streetlights-mqtt.yml
  src/examples/websocket-gemini.yml
Labels: autoapproved, ready-to-merge

#229 feat: add integration with AsyncAPI Server API
  .eslintrc
  package-lock.json
  package.json
  scripts/template-parameters.ts
  src/components/Editor/EditorDropdown.tsx
  src/components/Modals/ConfirmModal.tsx
  src/components/Modals/Generator/GeneratorModal.tsx
  src/components/Modals/Generator/TemplateParameters.tsx
  src/components/Modals/Generator/template-parameters.json
  src/components/Modals/Settings/SettingsModal.tsx
  src/components/Modals/index.tsx
  src/services/index.ts
  src/services/server-api.service.ts
  tsconfig.json
Labels: enhancement, ready-to-merge

#271 fix: failing tests for newer versions of the converter
  package-lock.json
  package.json
  src/services/specification.service.ts
  src/services/tests/specification.service.test.ts
Labels: dependencies
