Repository asyncapi/studio, pull requests merged in 2022-03, with the labels that each got.

#283 chore: replace @github-actions[bot] with @asyncapi-bot-eve
  CODEOWNERS
Labels: ready-to-merge, area/ci-cd

#282 feat: add a modal with information about what has changed in relation to the playground.
  src/components/Content.tsx
  src/components/Modals/ConfirmModal.tsx
  src/components/Modals/RedirectedModal.tsx
  src/components/Modals/index.tsx
  src/components/Visualiser/Nodes/ApplicationNode.tsx
  src/components/common/Markdown.tsx
  src/components/common/index.ts
  src/services/navigation.service.ts
  src/state/app.ts
Labels: enhancement, ready-to-merge

#287 chore: add playground redirects
  public/_redirects
Labels: ready-to-merge

#294 chore: update all-contributors section
  .all-contributorsrc
  README.md
Labels: bug, ready-to-merge, 📑 docs

#299 chore: fix typo in Dockerfile
  Dockerfile
Labels: ready-to-merge
