Repository asyncapi/studio, pull requests merged in 2022-01, with the labels that each got.

#222 fix: update react-component to next-27 version
  package-lock.json
  package.json
Labels: dependencies

#238 fix: add support for avro and openapi formats
  package-lock.json
  package.json
  src/services/specification.service.ts
Labels: bug

#243 fix: gitter spelling
  src/examples/index.tsx
Labels: ready-to-merge

#240 feat: create Docker image
  .dockerignore
  Dockerfile
  README.md
  package-lock.json
  package.json
Labels: ready-to-merge

#244 fix: add titles to sidebar's nodes
  src/components/Modals/Settings/SettingsModal.tsx
  src/components/Sidebar.tsx
Labels: ready-to-merge

#248 feat: add support for configuring the base URL
  Dockerfile
  README.md
  public/index.html
  src/components/Toolbar.tsx
  src/index.tsx
Labels: autoapproved, ready-to-merge
