Repository asyncapi/studio, pull requests merged in 2022-12, with the labels that each got.

#518 refactor: switch to the nice-modal-react modal management
  package-lock.json
  package.json
  src/App.tsx
  src/components/Content.tsx
  src/components/Editor/EditorDropdown.tsx
  src/components/Editor/MonacoWrapper.tsx
  src/components/Modals/ConfirmModal.tsx
  src/components/Modals/ConvertModal.tsx
  src/components/Modals/ConvertToLatestModal.tsx
  src/components/Modals/Generator/GeneratorModal.tsx
  src/components/Modals/Generator/TemplateParameters.tsx
  src/components/Modals/ImportBase64Modal.tsx
  src/components/Modals/ImportURLModal.tsx
  src/components/Modals/NewFileModal.tsx
  src/components/Modals/RedirectedModal.tsx
  src/components/Modals/Settings/SettingsModal.tsx
  src/components/Modals/Settings/SettingsTabs.tsx
  src/components/Modals/index.tsx
  src/components/Sidebar.tsx
  src/components/Template/HTMLWrapper.tsx
  src/components/Template/TemplateSidebar.tsx
  src/components/Terminal/ProblemsTab.tsx
  src/components/Terminal/TerminalInfo.tsx
  src/components/Visualiser/Visualiser.tsx
  src/components/common/Markdown.tsx
  src/index.tsx
  src/services/editor.service.tsx
  src/services/index.ts
  src/services/specification.service.ts
  src/state/app.state.ts
  src/state/index.ts
  src/state/panels.state.ts
  src/state/settings.ts
  src/studio.tsx
Labels: enhancement, ready-to-merge

#520 refactor: remove old state management
  src/App.tsx
  src/components/Content.tsx
  src/components/Editor/Editor.tsx
  src/components/Editor/EditorDropdown.tsx
  src/components/Editor/EditorSidebar.tsx
  src/components/Editor/MonacoWrapper.tsx
  src/components/Modals/ConvertModal.tsx
  src/components/Modals/ConvertToLatestModal.tsx
  src/components/Modals/Generator/GeneratorModal.tsx
  src/components/Modals/Generator/TemplateParameters.tsx
  src/components/Modals/RedirectedModal.tsx
  src/components/Modals/Settings/SettingsModal.tsx
  src/components/Navigation.tsx
  src/components/Popovers/SurveyPopover.tsx
  src/components/Sidebar.tsx
  src/components/Template/HTMLWrapper.tsx
  src/components/Template/Template.tsx
  src/components/Template/TemplateSidebar.tsx
  src/components/Terminal/ProblemsTab.tsx
  src/components/Terminal/TerminalInfo.tsx
  src/components/Terminal/TerminalTabs.tsx
  src/components/Visualiser/Visualiser.tsx
  src/services/app.service.ts
  src/services/converter.service.ts
  src/services/editor.service.tsx
  src/services/format.service.ts
  src/services/index.ts
  src/services/monaco.service.ts
  src/services/navigation.service.ts
  src/services/parser.service.ts
  src/services/settings.service.ts
  src/services/socket-client.service.tsx
  src/services/specification.service.ts
  src/services/tests/converter.service.test.ts
  src/services/tests/editor.service.test.ts
  src/services/tests/navigation.service.test.ts
  src/services/tests/specification.service.test.ts
  src/state/app.ts
  src/state/documents.state.ts
  src/state/editor.ts
  src/state/files.state.ts
  src/state/index.state.ts
  src/state/index.ts
  src/state/other.state.ts
  src/state/parser.ts
  src/state/sidebar.ts
  src/state/spec.ts
  src/state/template.ts
  src/studio.tsx
Labels: enhancement, ready-to-merge

#521 refactor: remove bundled monaco workers from source code
  public/js/monaco/editor.worker.bundle.js
  public/js/monaco/json.worker.bundle.js
  public/js/monaco/yaml.worker.bundle.js
Labels: dependencies, ready-to-merge

#523 chore: add .asyncapi-tool.yaml file
  .asyncapi-tool.yaml
Labels: ready-to-merge, 📑 docs

#524 feat: new invalid asyncapi template
  src/components/Modals/NewFileModal.tsx
  src/examples/index.tsx
  src/examples/tutorials/invalid.yml
Labels: ready-to-merge

#531 fix: handling of url/base64 query parameters
  src/components/Editor/MonacoWrapper.tsx
  src/services/app.service.ts
  src/services/editor.service.tsx
  src/services/index.ts
  src/services/parser.service.ts
  src/state/files.state.ts
Labels: bug, ready-to-merge

#508 fix: does not fetch json-schema-07 from web.
  src/services/monaco.service.ts
Labels: bug, ready-to-merge

#529 fix: websocket-gemini payload example
  src/examples/websocket-gemini.yml
Labels: bug, ready-to-merge
