Repository asyncapi/studio, pull requests merged in 2023-11, with the labels that each got.

#835 fix: update old broken link to new one
  apps/studio/src/examples/tutorials/invalid.yml
Labels: ready-to-merge

#827 chore: Add Amzani as a code owner
  CODEOWNERS
Labels: ready-to-merge

#823 [ADR-0005] support component styling with tailwind css in design system
  doc/adr/0005-use-tailwind-in-design-system.md
Labels: ready-to-merge, kind/adr

#838 ci: fix issue metrics action
  .github/workflows/issues-metrics.yml
Labels: ready-to-merge

#830 chore: add missing issues templates
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/enhancement.md
  .github/ISSUE_TEMPLATE/pitch.yml
  .github/pull_request_template.md
Labels: ready-to-merge

#841 chore: make v3 default
  apps/studio/src/components/Content.tsx
  apps/studio/src/components/Modals/Settings/SettingsModal.tsx
  apps/studio/src/components/Sidebar.tsx
  apps/studio/src/components/Terminal/TerminalTabs.tsx
  apps/studio/src/services/specification.service.ts
  apps/studio/src/state/files.state.ts
  apps/studio/src/state/settings.state.ts
Labels: autoupdate

#846 ci: disable add to bet action
  .github/workflows/add-scope-to-bet.yml
Labels: ready-to-merge

#622 feat: add error toasts when loading from "url" query paramater
  apps/studio/src/services/app.service.ts
  apps/studio/src/state/app.state.ts
  apps/studio/src/studio.tsx
Labels: ready-to-merge

#848 fix: update official invalid example to match tutorial
  apps/studio/src/examples/tutorials/invalid.yml
Labels: ready-to-merge

#857 feat: update dependencies
  apps/studio/package.json
  package-lock.json
Labels: ready-to-merge

#842 feat: Add v3 examples
  apps/studio/src/examples/ibmmq.yml
  apps/studio/src/examples/index.tsx
  apps/studio/src/examples/real-world/gitter-streaming.yml
  apps/studio/src/examples/real-world/kraken-api-request-reply-filter.yml
  apps/studio/src/examples/real-world/slack-rtm.yml
  apps/studio/src/examples/simple.yml
  apps/studio/src/examples/streetlights-kafka.yml
  apps/studio/src/examples/streetlights-mqtt.yml
  apps/studio/src/examples/websocket-gemini.yml
Labels: ready-to-merge, autoupdate

#862 chore: add princerajpoot20 as code owner for ds and ui
  CODEOWNERS
Labels: ready-to-merge
