Repository asyncapi/studio, pull requests merged in 2023-07, with the labels that each got.

#708 feat: add operation icon component
  apps/design-system/src/components/OperationIcon.stories.tsx
  packages/ui/components/OperationIcon.tsx
  packages/ui/components/index.tsx
Labels: ready-to-merge

#711 feat: add slideover component
  apps/design-system/src/components/SlideOver.stories.tsx
  packages/ui/components/SlideOver.tsx
  packages/ui/components/index.tsx
Labels: ready-to-merge

#712 feat: add ProtocolBadge component
  apps/design-system/src/components/ProtocolBadge.stories.tsx
  apps/design-system/src/design-tokens/Icons.stories.mdx
  packages/tailwind-config/tailwind.config.js
  packages/ui/components/ProtocolBadge.tsx
  packages/ui/components/icons/AMQPIcon.tsx
  packages/ui/components/icons/AWSSNSIcon.tsx
  packages/ui/components/icons/AWSSQSIcon.tsx
  packages/ui/components/icons/GooglePubSubIcon.tsx
  packages/ui/components/icons/IBMMQIcon.tsx
  packages/ui/components/icons/KafkaIcon.tsx
  packages/ui/components/icons/MQTTIcon.tsx
  packages/ui/components/icons/NATSIcon.tsx
  packages/ui/components/icons/PulsarIcon.tsx
  packages/ui/components/icons/RedisIcon.tsx
  packages/ui/components/icons/SolaceIcon.tsx
  packages/ui/components/icons/StompIcon.tsx
  packages/ui/components/icons/WebSocketIcon.tsx
  packages/ui/components/icons/index.tsx
  packages/ui/components/index.tsx
Labels: ready-to-merge

#718 fix: update default background to dark of operation icon
  apps/design-system/src/components/OperationIcon.stories.tsx
  packages/ui/components/OperationIcon.tsx
Labels: ready-to-merge

#714 fix: add missing arg to installer layer
  apps/studio/Dockerfile
Labels: ready-to-merge, autoupdate

#713 ci: add ADR lint and PR validation
  .github/workflows/lint-pr-adr.yml
Labels: ready-to-merge

#723 chore: [ADR-002] use changesets to manage release
  doc/adr/0002-use-changesets-for-publishing-and-versioning.md
Labels: ready-to-merge

#706 chore: use changesets to manage release
  .changeset/config.json
  .github/workflows/if-nodejs-release.yml
  .github/workflows/publish-docker-image.yml
  .github/workflows/release.yml
  apps/design-system/.storybook/preview.js
  apps/design-system/package.json
  apps/design-system/src/components/DropdownMenu.stories.tsx
  apps/design-system/src/components/Logo.stories.tsx
  apps/design-system/src/components/Modal.stories.tsx
  apps/design-system/src/components/OperationIcon.stories.tsx
  apps/design-system/src/components/ProtocolBadge.stories.tsx
  apps/design-system/src/components/Sidebar.stories.tsx
  apps/design-system/src/components/SlideOver.stories.tsx
  apps/design-system/src/components/Toolbar.stories.tsx
  apps/design-system/src/components/Tooltip.stories.tsx
  apps/design-system/src/design-tokens/Icons.stories.mdx
  apps/studio/Dockerfile
  apps/studio/package.json
  package-lock.json
  package.json
  packages/eslint-config-custom/package.json
  packages/ui/package.json
Labels: ready-to-merge

#732 fix: some actions should have secrets.GH_TOKEN
  .github/workflows/add-scope-to-bet.yml
  .github/workflows/check-adr.yml
  .github/workflows/lint-pr-adr.yml
Labels: ready-to-merge

#698 feat: add pitch issue template
  .github/ISSUE_TEMPLATE/pitch.yml
Labels: ready-to-merge

#736 fix: adr linting
  .github/workflows/lint-pr-adr.yml
Labels: ready-to-merge

#741 chore: [ADR-0004] use RadixUI
  doc/adr/0004-use-radix-ui.md
Labels: ready-to-merge, autoupdate, kind/adr
