Repository asyncapi/studio, pull requests merged in 2024-09, with the labels that each got.

#1136 chore: add @Shurtu-gal as code owner
  CODEOWNERS
Labels: ready-to-merge

#1094 feat: add Cypress
  .dockerignore
  .sonarcloud.properties
  apps/studio-next/.eslintrc
  apps/studio-next/cypress.config.ts
  apps/studio-next/cypress/e2e/studio-ui.spec.cy.ts
  apps/studio-next/cypress/fixtures/example.json
  apps/studio-next/cypress/support/commands.ts
  apps/studio-next/cypress/support/e2e.ts
  apps/studio-next/next.config.js
  apps/studio-next/package.json
  apps/studio-next/scripts/template-parameters.ts
  apps/studio-next/src/app/api/v1/generate/route.tsx
  apps/studio-next/src/components/Editor/Editor.tsx
  apps/studio-next/src/components/Editor/ShareButton.tsx
  apps/studio-next/src/components/Modals/Generator/GeneratorModal.tsx
  apps/studio-next/src/components/Navigation.tsx
  apps/studio-next/src/components/Navigationv3.tsx
  apps/studio-next/src/components/Sidebar.tsx
  apps/studio-next/src/components/Toolbar.tsx
  apps/studio-next/src/components/common/Dropdown.tsx
  apps/studio-next/src/components/common/Switch.tsx
  apps/studio-next/src/services/converter.service.ts
  apps/studio-next/src/services/editor.service.tsx
  apps/studio-next/src/services/server-api.service.ts
  apps/studio/package.json
  apps/studio/src/services/converter.service.ts
  apps/studio/src/services/editor.service.tsx
  pnpm-lock.yaml
  turbo.json
Labels: ready-to-merge

#1139 fix: temporarily hard-lock `@asyncapi/converter` on `v1.5.0` as a hotfix (#1138)
  .changeset/popular-geese-rescue.md
  apps/studio-next/package.json
  apps/studio/package.json
  pnpm-lock.yaml
Labels: ready-to-merge

#1135 feat: implement sharing of document through netlify blobs
  .gitignore
  apps/studio-next/netlify.toml
  apps/studio-next/package.json
  apps/studio-next/src/components/Editor/EditorDropdown.tsx
  apps/studio-next/src/components/Editor/EditorSidebar.tsx
  apps/studio-next/src/components/Editor/ShareButton.tsx
  apps/studio-next/src/components/Modals/ImportUUIDModal.tsx
  apps/studio-next/src/components/Modals/index.tsx
  apps/studio-next/src/netlify/functions/share-retreive.ts
  apps/studio-next/src/netlify/functions/share-store.ts
  apps/studio-next/src/services/app.service.ts
  apps/studio-next/src/services/editor.service.tsx
  apps/studio-next/src/services/navigation.service.ts
  apps/studio-next/src/state/files.state.ts
  pnpm-lock.yaml
Labels: enhancement, ready-to-merge

#1120 feat : add studio tour for first time user
  .sonarcloud.properties
  apps/studio-next/package.json
  apps/studio-next/src/app/globals.css
  apps/studio-next/src/components/Editor/Editor.tsx
  apps/studio-next/src/components/Editor/EditorSidebar.tsx
  apps/studio-next/src/components/Navigationv3.tsx
  apps/studio-next/src/components/Sidebar.tsx
  apps/studio-next/src/components/StudioWrapper.tsx
  apps/studio-next/src/components/Template/HTMLWrapper.tsx
  apps/studio-next/src/components/Terminal/Terminal.tsx
  apps/studio-next/src/components/Toolbar.tsx
  apps/studio-next/src/helpers/driver.ts
  apps/studio-next/src/state/other.state.ts
  apps/studio/package.json
  apps/studio/src/App.tsx
  apps/studio/src/components/Editor/Editor.tsx
  apps/studio/src/components/Editor/EditorSidebar.tsx
  apps/studio/src/components/Navigationv3.tsx
  apps/studio/src/components/Sidebar.tsx
  apps/studio/src/components/Template/HTMLWrapper.tsx
  apps/studio/src/components/Terminal/Terminal.tsx
  apps/studio/src/components/Toolbar.tsx
  apps/studio/src/helpers/driver.ts
  apps/studio/src/main.css
  apps/studio/src/state/other.state.ts
  doc/adr/0008-use-studio-tour.md
  pnpm-lock.yaml
Labels: ready-to-merge, bounty
